Squashed commit of the following:
commit fdc629d8662e7f64404f61ec116d7896024dd509
Author: chigozieorunta <chigozieorunta@yahoo.com>
Date:   Tue May 19 11:00:56 2020 -0400

    Error: The  prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.

commit 81c8ead9a7356ea7d4c89b77fece1e9f64998530
Author: chigozieorunta <chigozieorunta@yahoo.com>
Date:   Tue May 19 11:00:42 2020 -0400

    Error with styling components